# Generated by Django 4.2.11 on 2024-06-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('result', models.JSONField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
